// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ratelimiter.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the RateLimiter module

	public static java.lang.String getLognode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("RateLimiter.Lognode");
	}

	/**
	* per second rate limit, default is 1 = 60/min, 0.5 = 30/min
	*/
	public static java.math.BigDecimal getRateLimit()
	{
		return (java.math.BigDecimal)Core.getConfiguration().getConstantValue("RateLimiter.RateLimit");
	}
}